import logging
import os

import CoNLL_k_sentences_util
import CoNLL_table_search_util
import CoNLL_util
import IO_csv_util
import IO_files_util
from get_first_csv import first_csv

logger = logging.getLogger(__name__)

# more imports (e.g., import CoNLL_clause_analysis_util) are called below under separate if statements

# RUN section ______________________________________________________________________________________________________________________________________________________


# the values of the GUI widgets MUST be entered in the command otherwise they will not be updated
def run_CoNLL_table_analyzer(
    inputFilename,
    inputDir,
    outputDir,
    openOutputFiles,
    chartPackage,
    dataTransformation,
    searchedCoNLLField,
    searchField_kw,
    postag_var,
    deprel,
    co_postag,
    co_deprel,
    Begin_K_sent_var,
    End_K_sent_var,
    all_analyses_var,
    all_analyses,
    search_token_var,
    WordNet_var,
    compute_sentence_var,
    k_sentences_var,
):
    """Analyze and search a CoNLL table produced by the parsers."""
    inputFilename = first_csv(inputDir)
    logger.info("Input filename for CoNLL table analyzer  %s", inputFilename)
    extra_GUIs_var = False
    global recordID_position, documentId_position, data, all_CoNLL_records
    recordID_position = 9  # NEW CoNLL_U
    documentId_position = 11  # NEW CoNLL_U

    config_filename = "NLP_default_IO_config.csv"
    filesToOpen = []  # Store all files that are to be opened once finished
    outputFiles = []

    if (
        not extra_GUIs_var
        and not all_analyses_var
        and not search_token_var
        and not WordNet_var
        and not compute_sentence_var
        and not k_sentences_var
    ):
        logger.info(
            "No option selected, no option has been selected.\n\nPlease, select an option by ticking a checkbox and try again."
        )

        return

    # if extra_GUIs_var.get():
    #     if 'Data manipulation' in extra_GUIs_menu_var.get():
    #     if 'Ngrams searches' in extra_GUIs_menu_var.get():
    #     if 'Word searches' in extra_GUIs_menu_var.get():
    #     if 'Wordnet' in extra_GUIs_menu_var.get():

    # Ngrams searches & VIEWER','Word searches

    if search_token_var and "e.g.: father" in searchField_kw:
        logger.info(
            "Search error, The 'Searched token' field must be different from 'e.g.: father'. Please, enter a CoNLL table token/word and try again."
        )

        return

    withHeader = True
    # TODO Chen we are reading inputFilename twice, once here then again as a dataframe
    data, header = IO_csv_util.get_csv_data(inputFilename, withHeader)
    if len(data) == 0:
        return
    all_CoNLL_records = CoNLL_util.CoNLL_record_division(data)
    if all_CoNLL_records is None:
        return
    if len(all_CoNLL_records) == 0:
        return

    # ANALYSES -----------------------------------------------------------------------------------

    if all_analyses_var:
        # # create a subdirectory of the output directory; should create a subdir with increasing number to avoid writing ver
        # outputDir_temp = IO_files_util.make_output_subdirectory(inputFilename, '', outputDir, label='CoNLL_analyses',
        #                                                    silent=True)
        # if outputDir_temp == '':
        #
        #
        if all_analyses == "*":
            pass
        else:
            pass

        # startTime=IO_user_interface_util.timed_alert(GUI_util.window,2000,'Analysis start', 'Started running CoNLL table ' + label + ' analyses at',
        #                                              True, '', True, '', False)

        outputDirSV = outputDir

        if all_analyses == "*" or all_analyses == "Clause analysis":
            # create a subdirectory of the output directory; should create a subdir with increasing number to avoid writing ver
            outputDir_temp = IO_files_util.make_output_subdirectory(
                inputFilename, "", outputDir, label="CoNLL_clause", silent=True
            )
            if outputDir_temp == "":
                return
            outputDir = outputDir_temp

            if "CoNLL" in inputFilename and "_nn_" in inputFilename:
                if all_analyses == "Clause analysis":
                    logger.info(
                        "Input file error, The CLAUSE analysis algorithm expects in input a CoNLL table generated by the Stanford CoreNLP PCFG parser, rather than the nn, neural network parser.\n\nOnly the PCFG parser exports clause tags.\n\nPlease check your input file and try again."
                    )

            if "CoNLL" in inputFilename and "_nn_" not in inputFilename:
                import CoNLL_clause_analysis_util

                outputFiles = CoNLL_clause_analysis_util.clause_stats(
                    inputFilename,
                    "",
                    outputDir,
                    data,
                    all_CoNLL_records,
                    openOutputFiles,
                    chartPackage,
                    dataTransformation,
                )
                if outputFiles is not None:
                    filesToOpen.extend(outputFiles)

        if all_analyses == "*" or all_analyses == "Noun analysis":
            # create a subdirectory of the output directory; should create a subdir with increasing number to avoid writing ver
            outputDir_temp = IO_files_util.make_output_subdirectory(
                inputFilename, "", outputDirSV, label="CoNLL_noun", silent=True
            )
            if outputDir_temp == "":
                return
            outputDir = outputDir_temp
            import CoNLL_noun_analysis_util

            outputFiles = CoNLL_noun_analysis_util.noun_stats(
                inputFilename,
                outputDir,
                data,
                all_CoNLL_records,
                openOutputFiles,
                chartPackage,
                dataTransformation,
            )
            if outputFiles is not None:
                filesToOpen.extend(outputFiles)

        if all_analyses == "*" or all_analyses == "Adjective analysis":
            # create a subdirectory of the output directory; should create a subdir with increasing number to avoid writing ver
            outputDir_temp = IO_files_util.make_output_subdirectory(
                inputFilename, "", outputDirSV, label="CoNLL_adjective", silent=True
            )
            if outputDir_temp == "":
                return
            outputDir = outputDir_temp
            import CoNLL_adjective_analysis_util

            outputFiles = CoNLL_adjective_analysis_util.adjective_stats(
                inputFilename,
                outputDir,
                data,
                all_CoNLL_records,
                openOutputFiles,
                chartPackage,
                dataTransformation,
            )
            if outputFiles is not None:
                filesToOpen.extend(outputFiles)

        if all_analyses == "*" or all_analyses == "Content/Function ratio analysis":
            # create a subdirectory of the output directory; should create a subdir with increasing number to avoid writing ver
            outputDir_temp = IO_files_util.make_output_subdirectory(
                inputFilename, "", outputDirSV, label="CoNLL_ratio", silent=True
            )
            if outputDir_temp == "":
                return
            outputDir = outputDir_temp
            import CoNLL_ratio_analysis_util

            outputFiles = CoNLL_ratio_analysis_util.compute_word_class_frequencies(
                inputFilename,
                outputDir,
                data,
                all_CoNLL_records,
                openOutputFiles,
                chartPackage,
                dataTransformation,
            )
            if outputFiles is not None:
                filesToOpen.extend(outputFiles)

        if all_analyses == "*" or all_analyses == "Adverb analysis":
            # create a subdirectory of the output directory; should create a subdir with increasing number to avoid writing ver
            outputDir_temp = IO_files_util.make_output_subdirectory(
                inputFilename, "", outputDirSV, label="CoNLL_adverb", silent=True
            )
            if outputDir_temp == "":
                return
            outputDir = outputDir_temp
            import CoNLL_adverb_analysis_util

            outputFiles = CoNLL_adverb_analysis_util.adverb_stats(
                inputFilename,
                outputDir,
                data,
                all_CoNLL_records,
                openOutputFiles,
                chartPackage,
                dataTransformation,
            )
            if outputFiles is not None:
                filesToOpen.extend(outputFiles)
        if all_analyses == "*" or all_analyses == "Verb analysis":
            # create a subdirectory of the output directory; should create a subdir with increasing number to avoid writing ver
            outputDir_temp = IO_files_util.make_output_subdirectory(
                inputFilename, "", outputDirSV, label="CoNLL_verb", silent=True
            )
            if outputDir_temp == "":
                return
            outputDir = outputDir_temp
            import CoNLL_verb_analysis_util

            outputFiles = CoNLL_verb_analysis_util.verb_stats(
                config_filename,
                inputFilename,
                outputDir,
                data,
                all_CoNLL_records,
                openOutputFiles,
                chartPackage,
                dataTransformation,
            )

            if outputFiles is not None:
                filesToOpen.extend(outputFiles)

        if all_analyses == "*" or all_analyses == "Function (junk/stop) words analysis":
            # create a subdirectory of the output directory; should create a subdir with increasing number to avoid writing ver
            outputDir_temp = IO_files_util.make_output_subdirectory(
                inputFilename, "", outputDirSV, label="CoNLL_stop", silent=True
            )
            if outputDir_temp == "":
                return
            outputDir = outputDir_temp
            import CoNLL_function_words_analysis_util

            outputFiles = CoNLL_function_words_analysis_util.function_words_stats(
                inputFilename,
                outputDir,
                data,
                all_CoNLL_records,
                openOutputFiles,
                chartPackage,
                dataTransformation,
            )
            if outputFiles is not None:
                filesToOpen.extend(outputFiles)

        # IO_user_interface_util.timed_alert(GUI_util.window,2000,'Analysis end',
        #                                    'Finished running CoNLL table ' + label + ' analyses at',
        #                                    True, '', True, startTime, False)

    # SEARCH -----------------------------------------------------------------------------------

    if search_token_var and searchField_kw != "e.g.: father":
        # # create a subdirectory of the output directory
        # outputDir = IO_files_util.make_output_subdirectory(inputFilename, '', outputDir, label='CoNLL_search',
        #                                                    silent=True)

        if " " in searchField_kw:
            logger.info(
                "Search error, The CoNLL table search can only contain one token/word since the table has one record for each token/word.\n\nPlease, enter a different word and try again.\n\nIf you need to search your corpus for collocations, i.e., multi-word expressions, you need to use the 'N-grams/Co-occurrence searches' or the 'Words/collocations searches' in the ALL searches GUI."
            )

            return
        if searchedCoNLLField.lower() not in ["lemma", "form"]:
            searchedCoNLLField = "FORM"
        if postag_var != "*":
            postag = str(postag_var).split(" - ")[0]
            postag = postag.strip()
        else:
            postag = "*"
        if deprel != "*":
            deprel = str(deprel).split(" - ")[0]
            deprel = deprel.strip()
        else:
            deprel = "*"
        if co_postag != "*":
            co_postag = str(co_postag).split(" - ")[0]
            co_postag = co_postag.strip()
        else:
            co_postag = "*"
        if co_deprel != "*":
            co_deprel = str(co_deprel).split(" - ")[0]
            co_deprel = co_deprel.strip()
        else:
            co_deprel = "*"

        if "e.g.: father" in searchField_kw:
            if (
                (not os.path.isfile(inputFilename.strip()))
                and ("CoNLL" not in inputFilename)
                and (not inputFilename.strip()[-4:] == ".csv")
            ):
                logger.info(
                    "INPUT File Path Error, Please, check INPUT FILE PATH and try again. The file must be a CoNLL table (extension .conll with Stanford CoreNLP no clausal tags, extension .csv with Stanford CoreNLP with clausal tags)"
                )

                return
            msg = "Please, check the 'Searched token' field and try again.\n\nThe value entered must be different from the default value (e.g.: father)."
            logger.info("Searched Token Input Error,  %s", msg)
            return  # breaks loop
        if len(searchField_kw) == 0:
            msg = "Please, check the 'Searched token' field and try again.\n\nThe value entered must be different from blank."
            logger.info("Searched Token Input Error,  %s", msg)
            return  # breaks loop

        # startTime=IO_user_interface_util.timed_alert(GUI_util.window,2000,'Analysis start', 'Started running CoNLL search at',
        #                                              True, '', True, '', True)

        withHeader = True
        data, header = IO_csv_util.get_csv_data(inputFilename, withHeader)

        if len(data) <= 1000000:
            try:
                data = sorted(data, key=lambda x: int(x[recordID_position]))
            except Exception:
                logger.info(
                    "CoNLL table ill formed, The CoNLL table is ill formed. You may have tinkered with it. Please, rerun the Stanford CoreNLP parser since many scripts rely on the CoNLL table."
                )

                return

        temp_outputDir, filesToOpen = CoNLL_table_search_util.search_CoNLL_table(
            inputFilename,
            outputDir,
            config_filename,
            chartPackage,
            dataTransformation,
            all_CoNLL_records,
            searchField_kw,
            searchedCoNLLField,
            related_token_POSTAG=co_postag,
            related_token_DEPREL=co_deprel,
            _tok_postag_=postag,
            _tok_deprel_=deprel,
        )

        if len(filesToOpen) > 0:
            outputDir = temp_outputDir

    # WordNet ------------------------------------------------------------------------------

    if WordNet_var:
        # create a subdirectory of the output directory; should create a subdir with increasing number to avoid writing ver
        outputDir_SV = outputDir
        outputDir = IO_files_util.make_output_subdirectory(
            inputFilename, "", outputDir, label="CoNLL_WordNet", silent=False
        )
        if outputDir == "":
            return

        import pandas as pd

        df = pd.read_csv(inputFilename)
        df_nouns = df[df["POS"].isin(["NN", "NNPS", "NNP", "NNS"])][["Lemma", "POS"]]
        inputFilename_nouns = outputDir + os.sep + "CoNLL_nouns_forWordNet.csv"
        df_nouns.to_csv(inputFilename_nouns, index=False)  # , header=None
        df_verbs = df[df["POS"].isin(["VB", "VBN", "VBD", "VBG", "VBP", "VBZ"])][["Lemma", "POS"]]
        inputFilename_verbs = outputDir + os.sep + "CoNLL_verbs_forWordNet.csv"
        df_verbs.to_csv(inputFilename_verbs, index=False)  # , header=None

        filesToOpen.append(inputFilename_nouns)
        filesToOpen.append(inputFilename_verbs)

        # the WordNet installation directory is now checked in aggregate_GoingUP
        WordNetDir = ""
        import knowledge_graphs_WordNet_util

        output = knowledge_graphs_WordNet_util.aggregate_GoingUP(
            WordNetDir,
            inputFilename_nouns,
            outputDir,
            config_filename,
            "NOUN",
            openOutputFiles,
            chartPackage,
            dataTransformation,
            language_var="English",
        )
        if output is not None:
            if isinstance(output, str):
                filesToOpen.append(output)
            else:
                filesToOpen.extend(output)

        output = knowledge_graphs_WordNet_util.aggregate_GoingUP(
            WordNetDir,
            inputFilename_verbs,
            outputDir,
            config_filename,
            "VERB",
            openOutputFiles,
            chartPackage,
            dataTransformation,
            language_var="English",
        )
        if output is not None:
            if isinstance(output, str):
                filesToOpen.append(output)
            else:
                filesToOpen.extend(output)

        outputDir = outputDir_SV

    # -----------------------------------------------------------------------------------------------------------------------------
    if compute_sentence_var:
        tempOutputFile = CoNLL_util.compute_sentence_table(inputFilename, outputDir)
        filesToOpen.append(tempOutputFile)

    # -----------------------------------------------------------------------------------------------------------------------------
    if k_sentences_var:
        if Begin_K_sent_var == 0 or End_K_sent_var == 0:
            logger.info(
                "Warning, The Repetion finder algorithm needs beginning and end K sentences.\n\nPlease, enter valid K number(s) of sentences and try again."
            )

            return
        # startTime = IO_user_interface_util.timed_alert(GUI_util.window, 2000, 'Analysis start',
        #                                                'Started running the CoNLL table K-sentences analyzer at',
        #                                                True, '', True, '', False)
        temp_outputDir, outputFiles = CoNLL_k_sentences_util.k_sent(
            inputFilename,
            outputDir,
            chartPackage,
            dataTransformation,
            Begin_K_sent_var,
            End_K_sent_var,
        )
        if outputFiles is not None:
            outputDir = temp_outputDir
            filesToOpen.extend(outputFiles)

        # IO_user_interface_util.timed_alert(GUI_util.window,2000,'Analysis end',
        #                                    'Finished running the CoNLL table K-sentences analyzer at',
        #                                    True, '', True, startTime, False)

    # if openOutputFiles:
