import logging

# Written by Roberto Franzosi
# Modified by Cynthia Dong (Fall 2019-Spring 2020)
# Wordnet_bySentenceID and get_case_initial_row written by Yi Wang (April 2020)
import config_util
import CoNLL_util
import html_annotator_dictionary_util
import IO_files_util
import IO_libraries_util
import knowledge_graphs_WordNet_util
import pandas as pd
import Stanford_CoreNLP_util
from util import collect

logger = logging.getLogger(__name__)

# RUN section ______________________________________________________________________________________________________________________________________________________

pd.set_option("display.max_columns", 500)
# DocumentID    DocumentName    SenetenceID     (FullSentence)
# written by Yi Wang April 2020


def run_kg_wordnet(
    inputFilename,
    inputDir,
    outputDir,
    openOutputFiles,
    chartPackage,
    dataTransformation,
    csv_file,
    aggregate_POS_var,
    noun_verb,
    disaggregate_var,
    wordNet_keyword_list,
    annotate_file_var,
    extract_proper_nouns,
    extract_improper_nouns,
    aggregate_lemmatized_var,
    extract_nouns_verbs_from_CoNLL_var,
    aggregate_bySentenceID_var,
    dict_WordNet_filename_var,
    hidden_noun_lemma_csv,  # added
    hidden_verb_lemma_csv,
    noun_verb_menu_var,
):
    """Build WordNet knowledge-graph tables/charts for the selected words."""
    config_filename = "NLP_default_IO_config.csv"
    filesToOpen = []  # Store all files that are to be opened once finished
    # get the NLP package and language options
    (
        error,
        package,
        parsers,
        package_basics,
        language,
        package_display_area_value,
        encoding_var,
        export_json_var,
        memory_var,
        document_length_var,
        limit_sentence_length_var,
    ) = config_util.read_NLP_package_language_config()

    language_var = "English"  # WordNet works only for English language

    WordNetDir, existing_software_config, errorFound = IO_libraries_util.external_software_install(
        "knowledge_graphs_WordNet_util",
        "WordNet",
        "",
        silent=False,
        errorFound=False,
    )
    if WordNetDir is None:
        return filesToOpen

    if (
        not aggregate_POS_var
        and not disaggregate_var
        and not annotate_file_var
        and not aggregate_lemmatized_var
        and not aggregate_bySentenceID_var
        and not extract_nouns_verbs_from_CoNLL_var
        and not extract_proper_nouns
        and not extract_improper_nouns
    ):
        logger.info(
            "Missing required information, No options have been selected.\n\nPlease, tick one of the available options and try again."
        )
        return False

    if disaggregate_var and len(wordNet_keyword_list) == 0:
        logger.info(
            "Missing required information, You have selected to run the option 'Zoom IN/DOWN to find related words', but you have not entered any keywords required to run the script.\n\nPlease, enter the keywords and try again."
        )
        return False

    if disaggregate_var:
        filesToOpen = knowledge_graphs_WordNet_util.disaggregate_GoingDOWN(
            WordNetDir, outputDir, wordNet_keyword_list, noun_verb
        )
        if len(filesToOpen) > 0:
            str(filesToOpen[0])

    if annotate_file_var:
        if not IO_libraries_util.check_inputPythonJavaProgramFile(
            "html_annotator_dictionary_util.py"
        ):  # Check if the scrit is here
            return
        else:
            import IO_csv_util

            if csv_file != "":
                headers = IO_csv_util.get_csvfile_headers(csv_file)
            else:
                logger.info(
                    "Option not available, You have selected to run the option 'Annotate corpus' but you have not selected a csv input file.\n\nPlease, select an INPUT csv file and try again."
                )
                return
            sel_col = ""
            # Word is the term used by other scripts; but the WordNet script uses Term; just in case we change that...
            if "Term" == headers[0]:
                sel_col = "Term"
            elif "Word" == headers[0]:
                sel_col = "Word"
            else:
                logger.info(
                    "Wrong input file, You have selected to run the option 'Annotate corpus' but the selected input csv file is NOT a file generated by the Zoom IN/DOWN algorithm. Only that type of csv file is admitted; that file should have the header 'Term'.\n\nPlease, select the expected csv file and try again."
                )
                return

        csvValue_color_list = []
        bold_var = True
        color_palette_dict_var = "red"  # default color, if forgotten

        tagAnnotations = [
            '<span style="color: ' + color_palette_dict_var + '; font-weight: bold">',
            "</span>",
        ]

        filesToOpen = html_annotator_dictionary_util.dictionary_annotate(
            inputFilename,
            inputDir,
            outputDir,
            config_filename,
            csv_file,
            sel_col,
            csvValue_color_list,
            bold_var,
            tagAnnotations,
            ".txt",
            "WordNet_" + noun_verb,
        )

    if extract_proper_nouns == 1 or extract_improper_nouns == 1:
        import IO_csv_util

        if csv_file != "":
            headers = IO_csv_util.get_csvfile_headers(csv_file)
        else:
            logger.info(
                "Option not avaialble, You have selected to run the option 'Extract PROPER/IMPROPER nouns' but you have not selected a csv input file.\n\nPlease, select an INPUT csv file and try again."
            )
            return
        sel_col = ""
        # Word is the term used by other scripts; but the WordNet script uses Term; just in case we change that...
        if "Term" == headers[0]:
            sel_col = "Term"
        elif "Word" == headers[0]:
            sel_col = "Word"
        else:
            logger.info(
                "Wrong input file, You have selected to run the option 'Extract PROPER/IMPROPER nouns' but the selected input csv file is NOT a file generated by the Zoom IN/DOWN algorithm. Only that type of csv file is admitted; that file should have the header 'Term'.\n\nPlease, select the expected csv file and try again."
            )
            return
        if noun_verb != "NOUN":
            logger.info(
                "Option not available, You have selected to run the option 'Extract PROPER/IMPROPER nouns' with VERB.\n\nPlease, select NOUN and try again."
            )
            return
        if len(csv_file) == 0:
            logger.info(
                "Missing input file, You have selected to run the option 'Extract PROPER/IMPROPER nouns'. The algorithm expects in input a WordNet dictionary file previously exported with the 'Zoom IN/DOWN' algorithm for nouns.\n\nPlease, select an input WordNet dictionary file and try again."
            )
            return
        if extract_proper_nouns:
            filesToOpen = knowledge_graphs_WordNet_util.get_case_initial_row(csv_file, outputDir, sel_col, True)
        if extract_improper_nouns:
            filesToOpen = knowledge_graphs_WordNet_util.get_case_initial_row(csv_file, outputDir, sel_col, False)

    if aggregate_lemmatized_var:
        if len(csv_file) == 0:
            logger.info(
                "Missing required information, You have selected to run the option 'Zoom OUT/UP to find higher-level aggregates', but you have not selected the Input csv file for "
                + noun_verb
                + " required to run the script.\n\nPlease, select the Input file and try again."
            )
            return False
        if noun_verb == "NOUN" and "nouns_lemma" not in csv_file:
            if hidden_noun_lemma_csv != "":
                pass
            else:
                logger.info(
                    "Missing required information, You have selected to run the option 'Zoom OUT/UP to find higher-level aggregates' with the 'NOUN' option but the csv file currently selected does not contain the expected subscript 'nouns_lemma'.\n\nIf this an overshigth, click on the Select INPUT CSV file button to select a different csv file and try again."
                )
                # result=mb.askokcancel(title='Missing required information',
                #              message="You have selected to run the option 'Zoom OUT/UP to find higher-level aggregates' with the 'NOUN' option but the csv file currently selected does not contain the expected subscript 'nouns_lemma'.\n\nIf this an overshigth, click on the Select INPUT CSV file button to select a different csv file and try again.")
                return
        if noun_verb == "VERB" and "verbs_lemma" not in csv_file:
            if hidden_verb_lemma_csv != "":
                pass
            else:
                logger.info(
                    "Missing required information, You have selected to run the option 'Zoom OUT/UP to find higher-level aggregates' with the 'VERB' option but the csv file currently selected does not contain the expected subscript 'verbs_lemma'.\n\nIf this an overshigth, click on the Select INPUT CSV file button to select a different csv file and try again."
                )
                result = False
                if not result:
                    return
        filesToOpen = knowledge_graphs_WordNet_util.aggregate_GoingUP(
            WordNetDir,
            csv_file,
            outputDir,
            config_filename,
            noun_verb,
            openOutputFiles,
            chartPackage,
            dataTransformation,
            language_var,
        )

    if extract_nouns_verbs_from_CoNLL_var:
        # check that input file is a CoNLL table
        if not CoNLL_util.check_CoNLL(csv_file):
            return
        noun_form_csv, noun_lemma_csv, verb_form_csv, verb_lemma_csv = CoNLL_util.get_nouns_verbs_CoNLL(
            csv_file, outputDir
        )
        filesToOpen.append(noun_form_csv)
        filesToOpen.append(noun_lemma_csv)
        filesToOpen.append(verb_form_csv)
        filesToOpen.append(verb_lemma_csv)

        if noun_verb_menu_var == "NOUN":
            pass
        if noun_verb_menu_var == "VERB":
            pass
        hidden_verb_lemma_csv = verb_lemma_csv
        hidden_noun_lemma_csv = noun_lemma_csv

    if aggregate_POS_var:
        annotator = ["POS"]
        nouns_var = True
        verbs_var = True
        # uses a txt fie in input
        language_var = "English"
        files = Stanford_CoreNLP_util.CoreNLP_annotate(
            config_filename,
            inputFilename,
            inputDir,
            outputDir,
            openOutputFiles,
            chartPackage,
            dataTransformation,
            annotator,
            False,
            language_var,
            export_json_var,
            memory_var,
        )
        if len(files) > 0:
            noun_verb = ""
            if verbs_var:
                temp_csv_file = files[0]  # Verbs but... double check
                if "verbs" in temp_csv_file.lower():
                    noun_verb = "VERB"
                else:
                    return
                outputFiles = knowledge_graphs_WordNet_util.aggregate_GoingUP(
                    WordNetDir,
                    temp_csv_file,
                    outputDir,
                    config_filename,
                    noun_verb,
                    openOutputFiles,
                    chartPackage,
                    dataTransformation,
                    language_var,
                )
                if outputFiles is not None:
                    collect(filesToOpen, outputFiles)

            if nouns_var:
                temp_csv_file = files[1]  # Nouns but... double check
                if "nouns" in temp_csv_file.lower():
                    noun_verb = "NOUN"
                else:
                    return
                outputFiles = knowledge_graphs_WordNet_util.aggregate_GoingUP(
                    WordNetDir,
                    temp_csv_file,
                    outputDir,
                    config_filename,
                    noun_verb,
                    openOutputFiles,
                    chartPackage,
                    dataTransformation,
                    language_var,
                )
                if outputFiles is not None:
                    collect(filesToOpen, outputFiles)

    if aggregate_bySentenceID_var == 1:
        # check that input file is a CoNLL table
        if not CoNLL_util.check_CoNLL(csv_file):
            return
        outputFilename = IO_files_util.generate_output_file_name(csv_file, outputDir, ".csv", "WordNet", "conll")
        filesToOpen.append(outputFilename)
        outputFiles = knowledge_graphs_WordNet_util.Wordnet_bySentenceID(
            csv_file,
            dict_WordNet_filename_var,
            outputFilename,
            outputDir,
            noun_verb,
            openOutputFiles,
            chartPackage,
            dataTransformation,
        )
        if outputFiles is not None:
            collect(filesToOpen, outputFiles)
