import time
import tkinter as tk
import tkinter.messagebox as mb

def timed_alert(window,timeout,message_title,message_text,time_needed=False,extraLine='',printInCommandLine=True):
    if time_needed==True:
        time_report = time.localtime()
        message_text=message_text+' '+str(time_report[3]) + ':' + str(time_report[4])+'.'
    if len(extraLine)>0:
        message_text=message_text + '\n\n' + extraLine
    top_message = tk.Toplevel(window)
    top_message.title(message_title)
    # windowHeight=len(message_text)
    # print("windowHeight",windowHeight)
    windowHeight=200
    windowSize='400x200' #+str(windowHeight)
    top_message.geometry(windowSize)

    mbox = tk.Message(top_message, text=message_text, padx=20,pady=20,width=260)
    top_message.attributes('-topmost', 'true')
    mbox.after(timeout,top_message.destroy)
    mbox.pack()
    button = tk.Button(top_message, text="OK", command=top_message.destroy)
    button.pack()
    top_message.wait_window()
    # if ('Started running' in message_text) or ('Finished running' in message_text):
    if printInCommandLine:
        print('\n'+message_text+'\n')
    window.focus_force()

def input_output_save(script):
    result = mb.askyesno(script,
                         script + " will save changes directly in the input file. Make sure you have backup of the input.\n\nAre you sure you want to continue?")
    if result == False:  # yes no False
        return False
    else:
        return True

def single_file_output_save(inputDir,script):
    if len(inputDir) != 0:
        mb.showwarning(title='Warning', message='The output filename generated by ' + script + ' is the name of the directory processed in input, rather than any individual file in the directory.\n\nThe output csv file includes all the files in the input directory processed by the script.')

def subdirectory_file_output_save(inputDir,inputSubdir, IO, script):
    if len(inputDir) != 0:
        mb.showwarning(title='Warning', message='The ' + script + ' script has saved output in \n\n  ' + inputSubdir + '\n\na subdirectory of the ' + IO + ' directory\n\n  ' + inputDir)
