#Written by Roberto Franzosi
#Modified by Cynthia Dong (Fall 2019-Spring 2020)
#Wordnet_bySentenceID written by Yi Wang (April 2020)

import sys
import GUI_util
import IO_libraries_util

if IO_libraries_util.install_all_Python_packages(GUI_util.window,"semantic_aggregation_FrameNet_VerbNet_WordNet_main",['os','tkinter','pandas'])==False:
    sys.exit(0)

import os
import tkinter as tk
from tkinter import ttk
import tkinter.messagebox as mb
import pandas as pd

import GUI_IO_util
import config_util
import IO_files_util
import CoNLL_util
import semantic_aggregation_WordNet_util
import semantic_aggregation_util
import sentence_analysis_util
import reminders_util
import html_annotator_dictionary_util
import run_script_util

# RUN section ______________________________________________________________________________________________________________________________________________________

pd.set_option('display.max_columns', 500)
# DocumentID    DocumentName    SenetenceID     (FullSentence)
# written by Yi Wang April 2020

def run(inputFilename, inputDir, outputDir,openOutputFiles,
        chartPackage,
        dataTransformation,
        csv_file,
        noun_verb,
        knowledge_base,
        disambiguate_var,
        disaggregate_var,
        wordNet_keyword_list,
        annotate_file_var,
        aggregate_lemmatized_var,
        extract_nouns_verbs_from_CoNLL_var,
        aggregate_bySentenceID_var,
        dict_WordNet_filename_var):

    config_filename = GUI_util.config_filename_selected_config.get()
    filesToOpen = []  # Store all files that are to be opened once finished

    # get the NLP package and language options
    error, package, parsers, package_basics, language, package_display_area_value, encoding_var, export_json_var, memory_var, document_length_var, limit_sentence_length_var = config_util.read_NLP_package_language_config()

    language_var='English' # WordNet works only for English language

    # NLTK bundles WordNet — no external install needed
    WordNetDir = ''

    # print("noun_verb",noun_verb)

    if disambiguate_var==False and disaggregate_var==False and annotate_file_var== False and aggregate_lemmatized_var==False and aggregate_bySentenceID_var==False and extract_nouns_verbs_from_CoNLL_var==False:
        mb.showerror(title='Missing required information', message="No options have been selected.\n\nPlease, tick one of the available options and try again.")
        return False

    if disaggregate_var==True and len(wordNet_keyword_list)==0:
        mb.showerror(title='Missing required information', message="You have selected to run the option 'Zoom IN/DOWN to find related words', but you have not entered any keywords required to run the script.\n\nPlease, enter the keywords and try again.")
        return False

    if disaggregate_var==True:
        if knowledge_base == '*' or knowledge_base == '':
            mb.showerror(title='Select a specific Knowledge base',
                         message="Zoom IN/DOWN builds a list from one category, which belongs to a single resource (a WordNet synset, a VerbNet class, or a FrameNet frame).\n\nPlease choose WordNet, VerbNet, or FrameNet (not *) for the Knowledge base and try again.")
            return False
        filesToOpen= semantic_aggregation_util.disaggregate(knowledge_base, WordNetDir, outputDir, wordNet_keyword_list, noun_verb)
        if len(filesToOpen)>0:
            csv_file_var.set(str(filesToOpen[0]))

    if annotate_file_var:
        if IO_libraries_util.check_inputPythonJavaProgramFile('html_annotator_dictionary_util.py') == False:
            return
        else:
            import IO_csv_util
            if csv_file != '':
                headers = IO_csv_util.get_csvfile_headers(csv_file)
            else:
                mb.showerror(title='Option not available',
                             message="You have selected to run the option 'Annotate corpus' but you have not selected a csv input file.\n\nPlease, select an INPUT csv file and try again.")
                return
            sel_col = ''
            # Word is the term used by other scripts; but the WordNet script uses Term; just in case we change that...
            if 'Term' == headers[0]:
                sel_col = 'Term'
            elif 'Word' == headers[0]:
                sel_col = 'Word'
            else:
                mb.showerror(title='Wrong input file',
                             message="You have selected to run the option 'Annotate corpus' but the selected input csv file is NOT a file generated by the Zoom IN/DOWN algorithm. Only that type of csv file is admitted; that file should have the header 'Term'.\n\nPlease, select the expected csv file and try again.")
                return

        csvValue_color_list = []
        bold_var=True
        color_palette_dict_var = 'red'  # default color, if forgotten

        tagAnnotations = ['<span style=\"color: ' + color_palette_dict_var + '; font-weight: bold\">', '</span>']

        filesToOpen = html_annotator_dictionary_util.dictionary_annotate(inputFilename, inputDir, outputDir,
                                                                    config_filename,
                                                                    csv_file, sel_col, csvValue_color_list,
                                                                    bold_var, tagAnnotations, '.txt','WordNet_'+noun_verb, lemmatize=True)

    if aggregate_lemmatized_var==True:

        if len(csv_file)==0:
            mb.showerror(title='Missing required information', message="You have selected to run the option 'Zoom OUT/UP to find higher-level aggregates', but you have not selected the Input csv file for " + noun_verb + " required to run the script.\n\nPlease, select the Input file and try again.")
            return False
        if noun_verb=='NOUN' and 'nouns_lemma' not in csv_file:
            if hidden_noun_lemma_csv.get() != '':
                csv_file_var.set(hidden_noun_lemma_csv.get())
            else:
                result=mb.askokcancel(title='Missing required information',
                             message="You have selected to run the option 'Zoom OUT/UP to find higher-level aggregates' with the 'NOUN' option but the csv file currently selected does not contain the expected subscript 'nouns_lemma'.\n\nIf this an overshigth, click on the Select INPUT CSV file button to select a different csv file and try again.")
                if result == False:
                    return
        if noun_verb=='VERB' and 'verbs_lemma' not in csv_file:
            if hidden_verb_lemma_csv.get()!='':
                csv_file_var.set(hidden_verb_lemma_csv.get())
            else:
                result=mb.askokcancel(title='Missing required information', message="You have selected to run the option 'Zoom OUT/UP to find higher-level aggregates' with the 'VERB' option but the csv file currently selected does not contain the expected subscript 'verbs_lemma'.\n\nIf this an overshigth, click on the Select INPUT CSV file button to select a different csv file and try again.")
                if result==False:
                    return
        filesToOpen = semantic_aggregation_util.aggregate(knowledge_base, WordNetDir, csv_file, outputDir, config_filename, noun_verb, openOutputFiles,
                                                     chartPackage, dataTransformation, language_var, wordNet_keyword_list)

    if extract_nouns_verbs_from_CoNLL_var==True:
        # check that input file is a CoNLL table
        if not CoNLL_util.check_CoNLL(csv_file):
            return
        noun_form_csv,noun_lemma_csv,verb_form_csv,verb_lemma_csv = CoNLL_util.get_nouns_verbs_CoNLL(csv_file, outputDir)
        filesToOpen.append(noun_form_csv)
        filesToOpen.append(noun_lemma_csv)
        filesToOpen.append(verb_form_csv)
        filesToOpen.append(verb_lemma_csv)

        if noun_verb_menu_var.get() == 'NOUN':
            csv_file_var.set(noun_lemma_csv)
        if noun_verb_menu_var.get() == 'VERB':
            csv_file_var.set(verb_lemma_csv)
        hidden_verb_lemma_csv.set(verb_lemma_csv)
        hidden_noun_lemma_csv.set(noun_lemma_csv)

    if aggregate_bySentenceID_var==1:
        # check that input file is a CoNLL table
        if not CoNLL_util.check_CoNLL(csv_file):
            return
        outputFilename=IO_files_util.generate_output_file_name(csv_file, outputDir, '.csv', 'WordNet', 'conll')
        filesToOpen.append(outputFilename)
        outputFiles = semantic_aggregation_WordNet_util.Wordnet_bySentenceID(csv_file,dict_WordNet_filename_var,outputFilename,outputDir,noun_verb,openOutputFiles,chartPackage, dataTransformation)
        if outputFiles != None:
            if isinstance(outputFiles, str):
                filesToOpen.append(outputFiles)
            else:
                filesToOpen.extend(outputFiles)

    if disambiguate_var==True:
        # Word Sense Disambiguation (WordNet): disambiguate each noun/verb IN CONTEXT (Lesk) from a CoNLL
        # table, then aggregate to the context-correct WordNet supersense - the precision alternative to the
        # bare-lemma first-sense aggregation. WordNet-only (VerbNet/FrameNet use the SRL/SemLink route).
        # NB: distinct from the Word2Vec GUI's BERT Word Sense INDUCTION (discovers senses, no inventory) -
        # see docs/Semantic_Aggregation_GUI_design.md section 8 (WSD vs WSI).
        if not CoNLL_util.check_CoNLL(csv_file):
            mb.showerror(title='Word sense disambiguation',
                         message="Word sense disambiguation needs a CoNLL table in input (it disambiguates each "
                                 "noun/verb using its sentence as context).\n\nPlease select a CoNLL table via the "
                                 "Select INPUT CSV file button and try again.")
            return
        outputFiles = semantic_aggregation_util.wsd_aggregate_WordNet(csv_file, outputDir, noun_verb, chartPackage, dataTransformation)
        if outputFiles:
            filesToOpen.extend(outputFiles)

    if openOutputFiles==True:
        IO_files_util.OpenOutputFiles(GUI_util.window, openOutputFiles, filesToOpen, outputDir, scriptName)

#the values of the GUI widgets MUST be entered in the command as widget.get() otherwise they will not be updated
run_script_command=lambda: run(GUI_util.inputFilename.get(),
                            GUI_util.input_main_dir_path.get(),
                            GUI_util.output_dir_path.get(),
                            GUI_util.open_csv_output_checkbox.get(),
                            GUI_util.charts_package_options_widget.get(),
                            GUI_util.data_transformation_options_widget.get(),
                            csv_file_var.get(),
                            noun_verb_menu_var.get(),
                            knowledge_base_menu_var.get(),
                            disambiguate_var.get(),
                            disaggregate_var.get(),
                            wordNet_keyword_list,
                            annotate_file_var.get(),
                            aggregate_lemmatized_var.get(),
                            extract_nouns_verbs_from_CoNLL_var.get(),
                            aggregate_bySentenceID_var.get(),
                            dict_WordNet_filename_var.get())

GUI_util.run_button.configure(command=run_script_command)

# GUI section ______________________________________________________________________________________________________________________________________________________

# the GUIs are all setup to run with a brief I/O display or full display (with filename, inputDir, outputDir)
#   just change the next statement to True or False IO_setup_display_brief=True
IO_setup_display_brief=True
GUI_size, y_multiplier_integer, increment = GUI_IO_util.GUI_settings(IO_setup_display_brief,
                             GUI_width=GUI_IO_util.get_GUI_width(3),
                             GUI_height_brief=600, # height at brief display
                             GUI_height_full=680, # height at full display
                             y_multiplier_integer=GUI_util.y_multiplier_integer,
                             y_multiplier_integer_add=2, # to be added for full display
                             increment=2)  # to be added for full display

GUI_label='Graphical User Interface (GUI) for FrameNet, VerbNet, WordNet tools'
head, scriptName = os.path.split(os.path.basename(__file__))
# hardcode the default config at module init: config_filename_selected_config is empty this early,
# which would make the startup I/O check falsely report the INPUT/OUTPUT fields as missing
config_filename = 'NLP_default_IO_config.csv'

# The 4 values of config_option refer to:
#   input file
        # 1 for CoNLL file
        # 2 for TXT file
        # 3 for csv file
        # 4 for any type of file
        # 5 for txt or html
        # 6 for txt or csv
#   input dir
#   input secondary dir
#   outputFiles dir
config_input_output_numeric_options=[2,1,0,1]

GUI_util.set_window(GUI_size, GUI_label, config_filename, config_input_output_numeric_options)

window = GUI_util.window
# config_input_output_numeric_options = GUI_util.config_input_output_numeric_options
# config_filename = GUI_util.config_filename
inputFilename = GUI_util.inputFilename
input_main_dir_path = GUI_util.input_main_dir_path
outputDir = GUI_util.output_dir_path

openOutputFiles = GUI_util.open_csv_output_checkbox.get()
# createCharts = GUI_util.create_chart_output_checkbox.get()

GUI_util.GUI_top(config_input_output_numeric_options, config_filename, IO_setup_display_brief, scriptName)

wordNet_keyword_list = []
hidden_noun_lemma_csv = tk.StringVar()
hidden_verb_lemma_csv = tk.StringVar()

extra_GUIs_var  = tk.IntVar()
extra_GUIs_menu_var = tk.StringVar()

FrameNet_var  = tk.IntVar()
VerbNet_var  = tk.IntVar()
WordNet_var  = tk.IntVar()
knowledge_base_menu_var = tk.StringVar()

# aggregate_var = tk.IntVar()
# build_word_list_var = tk.IntVar()

run_parser_var = tk.IntVar()

disambiguate_var = tk.IntVar()

aggregate_POS_var = tk.IntVar()
noun_verb_menu_var = tk.StringVar()
noun_verb_menu_var.set('NOUN')
disaggregate_var = tk.IntVar()
keyWord_var = tk.StringVar()
keyWord_entry_var = tk.StringVar()
aggregate_lemmatized_var = tk.IntVar()
extract_nouns_verbs_from_CoNLL_var = tk.IntVar()
annotate_file_var = tk.IntVar()
aggregate_bySentenceID_var = tk.IntVar()
dict_WordNet_filename_var = tk.StringVar()
csv_file_var= tk.StringVar()

def get_csv_file(window,title,fileType,displayFile):
    #csv_file_var.set('')
    initialFolder = os.path.dirname(os.path.abspath(__file__))
    filePath = tk.filedialog.askopenfilename(title = title, initialdir = initialFolder, filetypes = fileType)
    if len(filePath)>0 and displayFile:
        csv_file_var.set(filePath)
    return filePath


def find_semagg_csv(outputDir, inputFilename='', inputDir=''):
    """Newest-first list of semantic-aggregation input csvs for the corpus: lemma lists
    (*_nouns_lemma.csv / *_verbs_lemma.csv, for Zoom OUT/UP) and Zoom IN/DOWN word lists
    (NLP_*_DOWN_wordlist.csv, for Annotate). Matched by filename marker (Suite-produced, so the name is
    reliable). Thin wrapper over the shared CoNLL_util.find_corpus_csv discovery (no stem-narrowing)."""
    markers = ('nouns_lemma', 'verbs_lemma', 'down_wordlist')
    return CoNLL_util.find_corpus_csv(outputDir, inputFilename, inputDir,
                path_filter=lambda p: any(m in os.path.basename(p).lower() for m in markers),
                narrow_by_stem=False)


def select_input_csv(window):
    """'Select INPUT CSV file' button handler: offer the semantic-aggregation csvs found for the corpus
    (lemma lists + Zoom IN/DOWN word lists); fall back to a file dialog if none are found or the user browses."""
    chosen = IO_files_util.select_path_from_list(window,
                 find_semagg_csv(GUI_util.output_dir_path.get(), GUI_util.inputFilename.get(), GUI_util.input_main_dir_path.get()),
                 'Select a semantic-aggregation csv (a lemma list, or a Zoom IN/DOWN word-list dictionary), or browse for another file:',
                 title='Available semantic-aggregation csv files')
    if chosen is None:
        return ''
    if chosen != '__BROWSE__':
        filePath = chosen
    else:
        filePath = tk.filedialog.askopenfilename(title='Select INPUT csv file',
                                                 initialdir=os.path.dirname(os.path.abspath(__file__)),
                                                 filetypes=[("dictionary files", "*.csv")])
    if len(filePath) > 0:
        csv_file_var.set(filePath)
    return filePath


csv_file_button=tk.Button(window, width=GUI_IO_util.select_file_directory_button_width, text='Select INPUT CSV file',command=lambda: select_input_csv(window))
# csv_file_button.config(state='disabled')
y_multiplier_integer=GUI_IO_util.placeWidget(window,GUI_IO_util.labels_x_coordinate, y_multiplier_integer,csv_file_button,True)

#setup a button to open Windows Explorer on the selected input directory
openInputFile_button = tk.Button(window, width=GUI_IO_util.open_file_directory_button_width, text='', command=lambda: IO_files_util.openFile(window, csv_file_var.get()))
# the button widget has hover-over effects (no_hover_over_widget=False) and the info displayed is in text_info
# the two x-coordinate and x-coordinate_hover_over must have the same values
y_multiplier_integer = GUI_IO_util.placeWidget(window,
    GUI_IO_util.IO_configuration_menu,
    y_multiplier_integer,
    openInputFile_button, True, False, True, False, 90, GUI_IO_util.IO_configuration_menu, "Open INPUT csv file")

csv_file=tk.Entry(window, width=GUI_IO_util.WordNet_csv_file_width,textvariable=csv_file_var)
csv_file.config(state='disabled')
y_multiplier_integer=GUI_IO_util.placeWidget(window,GUI_IO_util.entry_box_x_coordinate, y_multiplier_integer,csv_file)

extra_GUIs_var.set(0)
extra_GUIs_checkbox = tk.Checkbutton(window, text='GUIs available for more analyses ', variable=extra_GUIs_var, onvalue=1, offvalue=0, command=lambda: activate_all_options())
# extra_GUIs_checkbox.configure(state='disabled')
y_multiplier_integer=GUI_IO_util.placeWidget(window,GUI_IO_util.labels_x_coordinate,y_multiplier_integer,extra_GUIs_checkbox,True)

extra_GUIs_menu_var.set('')
extra_GUIs_menu = tk.OptionMenu(window,extra_GUIs_menu_var,'Parsers and annotators','CoNLL table analyzer','Word Sense Induction (via BERT)')
# extra_GUIs_menu.configure(state='disabled')
# place widget with hover-over info
y_multiplier_integer = GUI_IO_util.placeWidget(window,GUI_IO_util.IO_configuration_menu, y_multiplier_integer,
                                   extra_GUIs_menu,
                                   False, False, True, False, 90, GUI_IO_util.IO_configuration_menu,
                                   "Select other related types of analysis you wish to perform" \
                                    "\nThe selected GUI will open without having to press RUN")

def open_GUI(*args):
    extra_GUIs_menu.configure(state='disabled')
    if extra_GUIs_var.get():
        extra_GUIs_menu.configure(state='normal')
    else:
        return
    if extra_GUIs_var.get():
        if 'Parser' in extra_GUIs_menu_var.get():
            run_script_util.run_script("parsers_annotators_main.py")
        elif 'CoNLL' in extra_GUIs_menu_var.get():
            run_script_util.run_script("CoNLL_table_analyzer_main.py")
        elif 'Sense' in extra_GUIs_menu_var.get():
            run_script_util.run_script("Word2Vec_main.py")
extra_GUIs_menu_var.trace('w',open_GUI)

lexical_category_lb = tk.Label(window, text='Lexical categories ')
y_multiplier_integer = GUI_IO_util.placeWidget(window,GUI_IO_util.labels_x_coordinate, y_multiplier_integer,
                                               lexical_category_lb,True)

noun_verb_menu = tk.OptionMenu(window, noun_verb_menu_var, 'NOUN', 'VERB')
noun_verb_menu.configure(width=9, state="normal")
y_multiplier_integer = GUI_IO_util.placeWidget(window,GUI_IO_util.entry_box_x_coordinate, y_multiplier_integer,
                                               noun_verb_menu)

knowledge_base_lb = tk.Label(window, text='Knowledge base ')
y_multiplier_integer = GUI_IO_util.placeWidget(window,GUI_IO_util.labels_x_coordinate, y_multiplier_integer,
                                               knowledge_base_lb,True)

knowledge_base_menu_var.set('*')
knowledge_base_menu = tk.OptionMenu(window, knowledge_base_menu_var, '*', 'FrameNet', 'VerbNet', 'WordNet')
knowledge_base_menu.configure(width=9, state="normal")
y_multiplier_integer = GUI_IO_util.placeWidget(window,GUI_IO_util.entry_box_x_coordinate, y_multiplier_integer,
                                               knowledge_base_menu)


# aggregate_var.set(0)
# aggregate_checkbox = tk.Checkbutton(window, text='Aggregate corpus words into categories', variable=disaggregate_var,
#                                     onvalue=1, offvalue=0, command=lambda: activate_all_options(noun_verb_menu_var.get()))
# # place widget with hover-over info
# y_multiplier_integer=GUI_IO_util.placeWidget(window,GUI_IO_util.labels_x_coordinate, y_multiplier_integer,
#                                              aggregate_checkbox,
#                                              False, False, True, False,
#                                              90, GUI_IO_util.labels_x_coordinate,
#                                              "Tick the checkbox to search the selected Knowledge base (WordNet synset, VerbNet class, or FrameNet frame) for related words in the selected category for NOUN or VERB.\n"
#                                              "The algorithm uses the selected lexical database only and does not use the input document(s) selected in the I/O configuration")

# build_word_list_var.set(0)
# build_word_list_checkbox = tk.Checkbutton(window, text='Build a word list from a selected lexical category', variable=build_word_list_var,
#                                     onvalue=1, offvalue=0, command=lambda: activate_all_options(build_word_list_var.get()))
# # place widget with hover-over info
# y_multiplier_integer=GUI_IO_util.placeWidget(window,GUI_IO_util.labels_x_coordinate, y_multiplier_integer,
#                                              build_word_list_checkbox,
#                                              False, False, True, False,
#                                              90, GUI_IO_util.labels_x_coordinate,
#                                              "Tick the checkbox to search the selected Knowledge base (WordNet synset, VerbNet class, or FrameNet frame) for related words in the selected category for NOUN or VERB.\n"
#                                              "The algorithm uses the selected lexical database only and does not use the input document(s) selected in the I/O configuration")

# Word Sense Disambiguation (WSD): disambiguate each noun/verb IN CONTEXT (Lesk) from a CoNLL table and
# aggregate to the context-correct WordNet supersense - the precision alternative to bare-lemma first-sense
# aggregation. WordNet-only (VerbNet/FrameNet use the SRL/SemLink route). Distinct from the Word2Vec GUI's
# BERT Word Sense INDUCTION (discovers senses, no inventory). See docs/Semantic_Aggregation_GUI_design.md sec 8.

CoNLL_button = tk.Button(window, text='CoNLL-based tools of semantic aggregation (Open GUI)', width=50, height=1, command=lambda: CoNLL_util.open_analyzer_for_current_corpus(run_parser_var.get()))
# place widget with hover-over info
y_multiplier_integer=GUI_IO_util.placeWidget(window,GUI_IO_util.labels_x_coordinate, y_multiplier_integer,
                                             CoNLL_button,
                                             True, False, True, False,
                                             90, GUI_IO_util.labels_x_coordinate,
                                             "Click to open the CoNLL table analyzer GUI.")

run_parser_var.set(0)
run_parser_checkbox = tk.Checkbutton(window, text='Run the default parser (Open GUI)', variable=run_parser_var,
                                    onvalue=1, offvalue=0, command=lambda: activate_all_options(disambiguate_var.get()))
# place widget with hover-over info
y_multiplier_integer=GUI_IO_util.placeWidget(window,GUI_IO_util.open_reminders_x_coordinate, y_multiplier_integer,
                                             run_parser_checkbox,
                                             False, False, True, False,
                                             90, GUI_IO_util.open_TIPS_x_coordinate,
                                             "Tick the checkbox to run the default parser on the currently selected I/O corpus and prepare the CoNLL table before opening the GUI.")

# "CoNLL-based tools of semantic aggregation. Run default parser and open CoNLL table analyser GUI"
# disambiguate_var.set(0)
# disambiguate_checkbox = tk.Checkbutton(window, text='Word sense disambiguation', variable=disambiguate_var,
#                                     onvalue=1, offvalue=0, command=lambda: activate_all_options(disambiguate_var.get()))
# # place widget with hover-over info
# y_multiplier_integer=GUI_IO_util.placeWidget(window,GUI_IO_util.labels_x_coordinate, y_multiplier_integer,
#                                              disambiguate_checkbox,
#                                              False, False, True, False,
#                                              90, GUI_IO_util.labels_x_coordinate,
#                                              "Tick the checkbox for Word Sense Disambiguation: each NOUN/VERB in a CoNLL table is disambiguated IN CONTEXT (Lesk algorithm) and aggregated to the context-correct WordNet category - the precision alternative to bare-lemma first-sense aggregation.\n"
#                                              "In INPUT it expects a CoNLL table (it uses each word's sentence as context). WordNet-only; VerbNet/FrameNet are disambiguated via the SRL route. (Sense DISAMBIGUATION against WordNet - distinct from the Word2Vec GUI's BERT sense INDUCTION, which discovers senses in your corpus.)")

# FrameNet_var.set(0)
# FrameNet_var_checkbox = tk.Checkbutton(window, text='FrameNet', variable=FrameNet_var,
#                                    onvalue=1, offvalue=0, command=lambda: activate_all_options(FrameNet_var.get()))
# # place widget with hover-over info
# y_multiplier_integer=GUI_IO_util.placeWidget(window,GUI_IO_util.labels_x_coordinate, y_multiplier_integer,
#                                              FrameNet_var_checkbox,
#                                              False, False, True, False,
#                                              90, GUI_IO_util.labels_x_coordinate,
#                                              "Tick the checkbox to select a csv file containing in the first column LEMMATIZED words (noun or verb, since WordNet only contains lemmatized values)" \
#                                              "\nLemmatized values will be used to find their WordNet aggregate value (e.g., the verb 'walk' as 'motion')")
#
# VerbNet_var.set(0)
# VerbNet_var_checkbox = tk.Checkbutton(window, text='VerbNet', variable=VerbNet_var,
#                                    onvalue=1, offvalue=0, command=lambda: activate_all_options(VerbNet_var.get()))
# # place widget with hover-over info
# y_multiplier_integer=GUI_IO_util.placeWidget(window,GUI_IO_util.labels_x_coordinate, y_multiplier_integer,
#                                              VerbNet_var_checkbox,
#                                              False, False, True, False,
#                                              90, GUI_IO_util.labels_x_coordinate,
#                                              "Tick the checkbox to select a csv file containing in the first column LEMMATIZED words (noun or verb, since WordNet only contains lemmatized values)" \
#                                              "\nLemmatized values will be used to find their WordNet aggregate value (e.g., the verb 'walk' as 'motion')")
#
# WordNet_var.set(0)
# WordNet_var_checkbox = tk.Checkbutton(window, text='WordNet', variable=WordNet_var,
#                                    onvalue=1, offvalue=0, command=lambda: activate_all_options(WordNet_var.get()))
# # place widget with hover-over info
# y_multiplier_integer=GUI_IO_util.placeWidget(window,GUI_IO_util.labels_x_coordinate, y_multiplier_integer,
#                                              WordNet_var_checkbox,
#                                              False, False, True, False,
#                                              90, GUI_IO_util.labels_x_coordinate,
#                                              "Tick the checkbox to select a csv file containing in the first column LEMMATIZED words (noun or verb, since WordNet only contains lemmatized values)" \
#                                              "\nLemmatized values will be used to find their WordNet aggregate value (e.g., the verb 'walk' as 'motion')")

disaggregate_var.set(0)
disaggregate_checkbox = tk.Checkbutton(window, text='Zoom IN/DOWN to find related words', variable=disaggregate_var,
                                    onvalue=1, offvalue=0, command=lambda: activate_all_options(noun_verb_menu_var.get()))
# place widget with hover-over info
y_multiplier_integer=GUI_IO_util.placeWidget(window,GUI_IO_util.labels_x_coordinate, y_multiplier_integer,
                                             disaggregate_checkbox,
                                             True, False, True, False,
                                             90, GUI_IO_util.labels_x_coordinate,
                                             "Tick the checkbox to search the selected Knowledge base (WordNet synset, VerbNet class, or FrameNet frame) for related words in the selected category for NOUN or VERB.\n"
                                             "The algorithm uses the selected lexical database only and does not use the input document(s) selected in the I/O configuration")

def activate_keyword_menu():
    # '+' button: add the current Combobox pick(s) to the list, then clear the box for the next pick
    global wordNet_keyword_list
    box = keyWord_entry_var.get().strip()
    if not box:
        return
    for x in box.split(','):
        x = x.strip()
        if x and x not in wordNet_keyword_list:
            wordNet_keyword_list.append(x)
    keyWord_entry_var.set('')
    try:
        keyWord_entry['values'] = list(semantic_aggregation_util.get_categories(knowledge_base_menu_var.get(), noun_verb_menu_var.get()))
    except tk.TclError:
        pass
    activate_all_options(noun_verb_menu_var.get())

add_keyword_button = tk.Button(window, text='+', width=GUI_IO_util.add_button_width, height=1, state='disabled',
                               command=lambda: activate_keyword_menu())
# place widget with hover-over info
y_multiplier_integer=GUI_IO_util.placeWidget(window,GUI_IO_util.entry_box_x_coordinate, y_multiplier_integer,
                                             add_keyword_button,
                                             True, False, True, False,
                                             90, GUI_IO_util.entry_box_x_coordinate,
                                             "Click on the + button to add another synset")

reset_keywords_button = tk.Button(window, text='Reset ', width=GUI_IO_util.reset_button_width, height=1, state='disabled',
                                  command=lambda: clear_keyword_list())
# place widget with hover-over info
y_multiplier_integer=GUI_IO_util.placeWidget(window,GUI_IO_util.WordNet_reset_pos, y_multiplier_integer,
                                             reset_keywords_button,
                                             True, False, True, False,
                                             90, GUI_IO_util.WordNet_reset_pos,
                                             "Click on the Reset button to clear currently selected synsets and start fresh")
def showKeywordList():
    mb.showwarning(title='Warning', message='The currently selected keywords are:\n\n' + ','.join(
        wordNet_keyword_list) + '\n\nPress OK to approve selection; press the RESET button (or ESCape) to start fresh and select different keywords.')

show_keywords_button = tk.Button(window, text='Show', width=GUI_IO_util.show_button_width, height=1, state='disabled',
                                 command=lambda: showKeywordList())
# place widget with hover-over info
y_multiplier_integer=GUI_IO_util.placeWidget(window,GUI_IO_util.WordNet_show_pos, y_multiplier_integer,
                                             show_keywords_button,
                                             True, False, True, False,
                                             90, GUI_IO_util.WordNet_show_pos,
                                             "Click on the Show button to display the currently selected synsets")

noun_verb_menu_options = []
keyWord_var.set('')
# keyWord_menu_lb = tk.Label(window, text='Pick a category ')
# y_multiplier_integer = GUI_IO_util.placeWidget(window,GUI_IO_util.WordNet_noun_verb_menu_pos, y_multiplier_integer,
#                                                keyWord_menu_lb, True)
#
# keyWord_menu = tk.OptionMenu(window, keyWord_var, noun_verb_menu_options)
# # place widget with hover-over info
# y_multiplier_integer=GUI_IO_util.placeWidget(window,GUI_IO_util.WordNet_keyWord_menu_pos+70, y_multiplier_integer,
#                                              keyWord_menu,
#                                              False, False, True, False,
#                                              90, GUI_IO_util.labels_x_coordinate,
#                                              "Pick a category for the selected Knowledge base: the list updates automatically to show WordNet top synsets (25 noun / 15 verb), the 429 VerbNet classes, or the 1,221 FrameNet frames. For a lower-level WordNet synset or a specific member word, type it in the 'Type a category' field instead.\n" \
#                                              "The use of this widget is mutually exclusive with the widget 'Type a category'. You can use one or the other.")

keyWord_entry_lb = tk.Label(window, text='Pick or type a category ')
y_multiplier_integer = GUI_IO_util.placeWidget(window,GUI_IO_util.open_reminders_x_coordinate, y_multiplier_integer,
                                               keyWord_entry_lb, True)

keyWord_entry = ttk.Combobox(window, width=GUI_IO_util.WordNet_keyWord_entry_width, textvariable=keyWord_entry_var, values=noun_verb_menu_options)
keyWord_entry.configure(state="disabled")
# place widget with hover-over info
y_multiplier_integer=GUI_IO_util.placeWidget(window,GUI_IO_util.WordNet_keyWord_menu_pos+70, y_multiplier_integer,
                                             keyWord_entry,
                                             True, False, True, False,
                                             90, GUI_IO_util.labels_x_coordinate,
                                             "Enter the comma-separated categories you want to use - a WordNet synset, VerbNet class, or FrameNet frame - for NOUN or VERB. Particularly useful for searching lower-level synsets (e.g., 'ethnic group' instead of 'person').\n" \
                                             "The use of this widget is mutually exclusive with the widget 'Pick a category'. You can use one or the other.")

OK_button = tk.Button(window, text='OK', width=GUI_IO_util.OK_button_width, height=1, state='disabled', command=lambda: accept_WordNet_list())
# the button widget has hover-over effects (no_hover_over_widget=False) and the info displayed is in text_info
# the two x-coordinate and x-coordinate_hover_over must have the same values
y_multiplier_integer = GUI_IO_util.placeWidget(window,
    GUI_IO_util.WordNet_OK_button_pos,
    y_multiplier_integer,
    OK_button, False, False, True, False, 90, GUI_IO_util.WordNet_keyWord_menu_pos, "Click OK when done entering the categories you typed. ")
#
#                                                OK_button)
def clear(e):
    if aggregate_lemmatized_var.get():
        aggregate_lemmatized_var.set(0)
    keyWord_var.set('')
    keyWord_entry_var.set('')
    dict_WordNet_filename_var.set('')
    csv_file_var.set('')
    GUI_util.clear("Escape")
window.bind("<Escape>", clear)


# activated when pressing the RESET button
def clear_keyword_list():
    wordNet_keyword_list.clear()
    keyWord_var.set('')
    keyWord_entry_var.set('')
    activate_all_options(noun_verb_menu_var.get())

def accept_WordNet_list():
    global wordNet_keyword_list
    # fold any value still in the box into the list (so a forgotten '+' isn't lost); supports comma-separated typing
    box = keyWord_entry_var.get().strip()
    if box:
        for x in box.split(','):
            x = x.strip()
            if x and x not in wordNet_keyword_list:
                wordNet_keyword_list.append(x)
        keyWord_entry_var.set('')
    if len(wordNet_keyword_list) == 0:
        mb.showwarning(title='Warning',
                       message='You have pressed the OK button, but you must first pick or type a category.\n\nPlease, select a category and try again.')
        return
    activate_all_options(noun_verb_menu_var.get())


def add_wordNet_keyword(*args):
    if keyWord_var.get() in wordNet_keyword_list:
        mb.showwarning(title='Warning',
                       message='The keyword "' + keyWord_var.get() + '" is already in your selection list: ' + str(
                           wordNet_keyword_list) + '.\n\nPlease, select another keyword.')
        window.focus_force()
        return
    if keyWord_var.get() != '':
        wordNet_keyword_list.append(noun_verb_menu_var.get().lower() + "." + keyWord_var.get())
        activate_all_options(noun_verb_menu_var.get())
keyWord_var.trace('w', add_wordNet_keyword)
keyWord_entry_var.trace('w', add_wordNet_keyword)

annotate_file_var.set(0)
annotate_file_checkbox = tk.Checkbutton(window, text='Annotate corpus (using csv output file from Zoom IN/DOWN)', variable=annotate_file_var, onvalue=1, offvalue=0, command=lambda: activate_all_options(noun_verb_menu_var.get(), True))
# place widget with hover-over info
y_multiplier_integer=GUI_IO_util.placeWidget(window,GUI_IO_util.labels_x_indented_coordinate, y_multiplier_integer,
                                             annotate_file_checkbox,
                                             False, False, True, False,
                                             90, GUI_IO_util.labels_x_coordinate,
                                             "Tick the checkbox to annotate your corpus in an html file.\nThe option automatically runs the default lemmatizer so inflected forms are tagged too (e.g., 'attacked', 'bombing' from 'attack', 'bomb'), each kept in its ORIGINAL form in the text.\nIn INPUT the algorithm expects the csv file generated by the Zoom IN/DOWN algorithm.")


aggregate_lemmatized_var.set(0)
aggregate_lemmatized_checkbox = tk.Checkbutton(window, text='Zoom OUT/UP (classify/aggregate lemmatized words in csv file)', variable=aggregate_lemmatized_var,
                                   onvalue=1, offvalue=0, command=lambda: activate_all_options(noun_verb_menu_var.get()))
# place widget with hover-over info
y_multiplier_integer=GUI_IO_util.placeWidget(window,GUI_IO_util.labels_x_coordinate, y_multiplier_integer,
                                             aggregate_lemmatized_checkbox,
                                             False, False, True, False,
                                             90, GUI_IO_util.labels_x_coordinate,
                                             "Tick the checkbox to select a csv file containing in the first column LEMMATIZED words (noun or verb)." \
                                             "\nThe lemmatized values are aggregated into the selected Knowledge base - a WordNet supersense (e.g., the verb 'walk' as 'motion'), a VerbNet class, or a FrameNet frame.")

# extract_nouns_verbs_from_CoNLL_var.set(0)
# extract_nouns_verbs_from_CoNLL_checkbox = tk.Checkbutton(window, text='Extract nouns & verbs from CoNLL table (for Zoom OUT/UP)',
#                                               variable=extract_nouns_verbs_from_CoNLL_var, onvalue=1, offvalue=0, command=lambda: activate_all_options(noun_verb_menu_var.get()))
# # place widget with hover-over info
# y_multiplier_integer=GUI_IO_util.placeWidget(window,GUI_IO_util.labels_x_indented_coordinate, y_multiplier_integer,
#                                              extract_nouns_verbs_from_CoNLL_checkbox,
#                                              False, False, True, False,
#                                              90, GUI_IO_util.labels_x_indented_coordinate,
#                                              "Tick the checkbox to extract the lemma values of nouns and verbs in a CoNLL table (lemmatized noun or verb, since WordNet only contains lemmatized values)" \
#                                              "\nLemmatized values will be used to find their WordNet aggregate value (e.g., the verb 'walk' as 'motion')")

aggregate_POS_var.set(0)
aggregate_POS_checkbox = tk.Checkbutton(window, text='Zoom OUT/UP (aggregate nouns & verbs from input text document(s) into WordNet, VerbNet, FrameNet categories)', variable=aggregate_POS_var,
                                    onvalue=1, offvalue=0, command=lambda: activate_all_options(noun_verb_menu_var.get()))
# place widget with hover-over info
y_multiplier_integer=GUI_IO_util.placeWidget(window,GUI_IO_util.labels_x_coordinate, y_multiplier_integer,
                                             aggregate_POS_checkbox,
                                             False, False, True, False,
                                             90, GUI_IO_util.labels_x_coordinate,
                                             "Tick the checkbox to run the default POS tagger that extracts NOUN and VERB POS tags and then aggregate these values into WordNet, VerbNet, FrameNet categories."
                                             "\nIn INPUT the algorithm expects a single txt file or a set of txt files."
                                             "\nIn OUTPUT the algorithm produces a csv file of POS tags with their WordNet/VerbNet/FrameNet category (e.g., the verb 'go' as the WordNet category 'motion').")

# aggregate_bySentenceID_var.set(0)
# # aggregate_bySentenceID_checkbox = tk.Checkbutton(window, text='Zoom OUT/UP by Sentence Index',
# #                                                 variable=aggregate_bySentenceID_var, onvalue=1, offvalue=0,
# #                                                 command=lambda: getDictFile())
# aggregate_bySentenceID_checkbox = tk.Checkbutton(window, text='Zoom OUT/UP by Sentence ID',
#                                                 variable=aggregate_bySentenceID_var, onvalue=1, offvalue=0, command=lambda: activate_all_options(noun_verb_menu_var.get()))
# # place widget with hover-over info
# y_multiplier_integer=GUI_IO_util.placeWidget(window,GUI_IO_util.labels_x_coordinate, y_multiplier_integer,
#                                              aggregate_bySentenceID_checkbox,
#                                              True, False, True, False,
#                                              90, GUI_IO_util.labels_x_coordinate,
#                                              "Tick the checkbox to run the algorithm that uses 1. lemmatized NOUN and VERB POS tags from a CoNLL table and 2. a dictionary of aggregated WordNet/VerbNet/FrameNet categories to visualize their occurrence in a text by sentence index."
#                                              "\nIn INPUT the algorithm expects 1. a CoNLL table and 2. a dictionary file of aggregated WordNet/VerbNet/FrameNet categories, created by the 'Zoom OUT/UP' widget above."
#                                              "\nIn OUTPUT the algorithm produces a csv file and a line plot by sentence index.")
#
# dict_WordNet_filename_lb = tk.Label(window, text='csv file of classified/aggregated words')
# # place widget with hover-over info
# y_multiplier_integer=GUI_IO_util.placeWidget(window,GUI_IO_util.WordNet_dict_WordNet_filename_lb_pos, y_multiplier_integer,
#                     dict_WordNet_filename_lb, True, False, True, False,
#                     90, GUI_IO_util.WordNet_dict_WordNet_filename_lb_pos,
#                     "The csv file is obtained by running the 'ZOOM OUT/UP (classify/aggregate lemmatized words in csv file)' widget above")
#
# # WordNet_keyWord_entry_width
# # dict_WordNet_filename = tk.Entry(window, width=GUI_IO_util.WordNet_dict_WordNet_filename_width, textvariable=dict_WordNet_filename_var)
# dict_WordNet_filename = tk.Entry(window, width=GUI_IO_util.WordNet_keyWord_entry_width, textvariable=dict_WordNet_filename_var)
# dict_WordNet_filename.configure(state="disabled")
# y_multiplier_integer = GUI_IO_util.placeWidget(window,GUI_IO_util.WordNet_keyWord_menu_pos, y_multiplier_integer,
#                                                dict_WordNet_filename, True)
#
# open_csv_file_button = tk.Button(window, width=GUI_IO_util.OK_button_width, height=1, state='disabled', command=lambda: accept_WordNet_list())
# y_multiplier_integer = GUI_IO_util.placeWidget(window,GUI_IO_util.WordNet_OK_button_pos, y_multiplier_integer,
#                                                open_csv_file_button)

asked = False

def activate_all_options(noun_verb, fromaggregate=False):
    global asked
    # all options FALSE
    # GUI_util.select_inputFilename_button.configure(state="disabled")
    # csv_file_var.set('')
    # csv_file_button.config(state='disabled')
    # disambiguate_checkbox.configure(state='normal')
    annotate_file_checkbox.configure(state='normal')
    aggregate_lemmatized_checkbox.configure(state='normal')
    # extract_nouns_verbs_from_CoNLL_checkbox.configure(state='normal')
    # aggregate_bySentenceID_checkbox.configure(state='normal')

    keyWord_entry.configure(state="disabled")
    add_keyword_button.configure(width=GUI_IO_util.add_button_width, height=1, state="disabled")
    reset_keywords_button.configure(width=GUI_IO_util.reset_button_width, height=1, state="disabled")

    if disaggregate_var.get() == True:
        aggregate_lemmatized_checkbox.configure(state='disabled')
        # keep Annotate available if a csv (the Zoom IN/DOWN output) is already listed
        if csv_file_var.get().strip() == '':
            annotate_file_checkbox.configure(state='disabled')
        # extract_nouns_verbs_from_CoNLL_checkbox.configure(state='disabled')
        # aggregate_bySentenceID_checkbox.configure(state='disabled')
        # single Pick-or-type Combobox: enable it, the + (add to list) and the OK button
        keyWord_entry.configure(state="normal")
        add_keyword_button.configure(width=GUI_IO_util.add_button_width, height=1, state="normal")
        OK_button.configure(state="normal")
        # RESET button: enabled when there is something to clear (box or accumulated list)
        if keyWord_entry_var.get() == '' and len(wordNet_keyword_list) == 0:
            reset_keywords_button.configure(width=GUI_IO_util.reset_button_width, height=1, state="disabled")
        else:
            reset_keywords_button.configure(width=GUI_IO_util.reset_button_width, height=1, state="normal")
    else:
        keyWord_var.set('')
        wordNet_keyword_list.clear()
        keyWord_entry_var.set('')
        dict_WordNet_filename_var.set('')

    if len(wordNet_keyword_list) > 0:
        show_keywords_button.configure(state="normal")
    else:
        show_keywords_button.configure(state="disabled")

    # RUN is always enabled. The required input differs by option (csv for the list-based options,
    # txt for the POS option, keywords for Zoom IN/DOWN) and the "no option selected" case are all
    # validated and warned about at RUN time in run().
    GUI_util.run_button.configure(state='normal')

    # else:
    #     asked = False

    if annotate_file_var.get() == 1:
        if csv_file_var.get()=='' and asked==False:
            asked=True
            mb.showwarning("csv dictionary file",
                           "Please, select next the csv dictionary file you want to use to annotate your txt file(s) then click on the RUN button.")
            filePath=get_csv_file(window, 'Select INPUT csv dictionary file', [("dictionary files", "*.csv")], True)
            if filePath=='':
                return
        csv_file_button.config(state='normal')
    # else:
    #     asked = False


    if aggregate_lemmatized_var.get() == 1: # aggregating UP
        if fromaggregate==False:
            if csv_file_var.get() == '' and asked==False:
                asked = True
                # mb.showwarning(title='csv WordNet dictionary',
                #                message="This is a reminder that you are searching WordNet for " + noun_verb_menu_var.get() + ".\n\nPlease, use the IO widget 'Select INPUT file' at the top of the GUI to select the csv file containing LEMMATIZED " + noun_verb_menu_var.get() + " values to be aggregated.\n\nThis file MUST contain LEMMATIZED " + noun_verb_menu_var.get() + " values, since WordNet only contains lemmatized values. If this is not the case, select a different NOUN/VERB option, and/or a different input file option.")
                mb.showwarning(title='Warning',
                               message='Please, select next the csv file containing in the first column the LEMMATIZED words (noun or verb, since WordNet only contains lemmatized values) for which you need to find their aggregate (e.g., the verb walk as motion).\n\nPlease, select next the INPUT csv file to be used.')
                filePath =get_csv_file(window, 'Select INPUT csv file', [("csv files", "*.csv")], True)
                if filePath == '':
                    return
        csv_file_button.config(state='normal')
        GUI_util.select_inputFilename_button.configure(state="normal")
        # disambiguate_checkbox.configure(state='disabled')
        annotate_file_checkbox.configure(state='disabled')
        # extract_nouns_verbs_from_CoNLL_checkbox.configure(state='disabled')
        # aggregate_bySentenceID_checkbox.configure(state='disabled')
    # else:
    #     asked = False

    if extract_nouns_verbs_from_CoNLL_var.get()==True:
        # disambiguate_checkbox.configure(state='disabled')
        annotate_file_checkbox.configure(state='disabled')
        aggregate_lemmatized_checkbox.configure(state='disabled')
        # aggregate_bySentenceID_checkbox.configure(state='disabled')
        if csv_file_var.get() == '' and asked==False:
            asked=True
            mb.showwarning("csv CoNLL table",
                           "Please, select next the csv CoNLL table from which you want to extract lemmatized nouns and verbs then click on the RUN button.")
            filePath = get_csv_file(window, 'Select INPUT csv CoNLL file', [("CoNLL files", "*.csv")],
                                           True)
            if filePath == '':
                return
    # else:
    #     asked = False

    asked = False

    # if aggregate_bySentenceID_var.get() == True:
    #     disaggregate_checkbox.configure(state='disabled')
    #     annotate_file_checkbox.configure(state='disabled')
    #     aggregate_lemmatized_checkbox.configure(state='disabled')
    #     # extract_nouns_verbs_from_CoNLL_checkbox.configure(state='disabled')
    #     mb.showwarning(title="Warning",
    #                    message="The Zoom OUT/UP by Sentence Index option requires in input 2 csv files:\n  1. a csv CoNLL file to get the sentence index;\n  2. a csv dictionary file containing the aggregated WordNet/VerbNet/FrameNet classification of LEMMATIZED words into top-level aggregates (synsets) and for which you want to see where in the text they are used (you will be prompted next to select this csv file; the file will have been generated by widget 'Zoom OUT/UP to top-level aggregates/synsets'). \n\nAs a reminder, you are searching in the CoNLL table for " + noun_verb_menu_var.get() + ". The selected dictionary file of aggregated words must also contain " + noun_verb_menu_var.get() + " values - values to be found in the input CoNLL file " + inputFilename.get() + "\n\nIf this is not the case, select a different NOUN/VERB option, and/or different input/output file options.")
    #     if csv_file_var.get() == '' and asked==False:
    #         asked=True
    #         mb.showwarning("csv CoNLL table",
    #                        "Please, select next the csv CoNLL table from which you want to extract lemmatized nouns and verbs then click on the RUN button.")
    #         filePath = get_csv_file(window, 'Select INPUT csv CoNLL file', [("CoNLL files", "*.csv")],
    #                                        True)
    #
    #         # filePath = get_csv_file(window, 'Select INPUT csv file of words classified/aggregated into WordNet synsets', [("csv files", "*.csv")],
    #         #                                False)
    #         if filePath == '':
    #             return
    #         mb.showwarning("csv WordNet dictionary",
    #                        "Please, select next the csv WordNet dictionary file generated by the ZOOM IN/DOWN algorithm then click on the RUN button.")
    #         filePath = get_csv_file(window, 'Select INPUT csv dictionary file', [("dictionary files", "*.csv")],
    #                                        False)
    #         if len(filePath) > 0:
    #             dict_WordNet_filename_var.set(filePath)
    #             GUI_util.select_inputFilename_button.configure(state='normal')
    #         else:
    #             # csv_file_var.set('')
    #             dict_WordNet_filename_var.set('')
    #             aggregate_bySentenceID_var.set(0)
    #     else:
    #         asked = False

activate_all_options(noun_verb_menu_var.get())

# set menu values
def setNounVerbMenu(*args):
    global noun_verb_menu_options
    noun_verb_menu_optionsSV = noun_verb_menu_options
    if noun_verb_menu_var.get() == 'NOUN':
        if hidden_noun_lemma_csv.get() != '':
            csv_file_var.set(hidden_noun_lemma_csv.get())
    else:
        if hidden_verb_lemma_csv.get() != '':
            csv_file_var.set(hidden_verb_lemma_csv.get())
    # KB-aware picker: WordNet top synsets (by NOUN/VERB), the 429 VerbNet classes, or the 1,221 FrameNet frames
    noun_verb_menu_options = tuple(semantic_aggregation_util.get_categories(knowledge_base_menu_var.get(), noun_verb_menu_var.get()))
    try:
        keyWord_entry['values'] = list(noun_verb_menu_options)
    except tk.TclError:
        pass  # keyWord_entry is still a plain Entry until swapped to a Combobox
    if noun_verb_menu_optionsSV != noun_verb_menu_options:
        clear_keyword_list()

    #print('hidden_noun_lemma_csv, hidden_verb_lemma_csv',hidden_noun_lemma_csv.get(), hidden_verb_lemma_csv.get())

noun_verb_menu_var.trace("w", setNounVerbMenu)
knowledge_base_menu_var.trace("w", setNounVerbMenu)

setNounVerbMenu()


def filter_category_combobox(event):
    # type-to-filter the Combobox dropdown against the current Knowledge base's categories
    if event.keysym in ('Up', 'Down', 'Return', 'Left', 'Right', 'Escape', 'Tab'):
        return
    typed = keyWord_entry_var.get().strip().lower()
    full = list(semantic_aggregation_util.get_categories(knowledge_base_menu_var.get(), noun_verb_menu_var.get()))
    try:
        keyWord_entry['values'] = full if not typed else [v for v in full if typed in v.lower()]
    except tk.TclError:
        pass  # keyWord_entry is still a plain Entry until swapped to a Combobox

try:
    keyWord_entry.bind('<KeyRelease>', filter_category_combobox)
except Exception:
    pass


def refresh_annotate_state(*args):
    # Annotate consumes a Zoom IN/DOWN csv, so enable it as soon as a csv is listed (even with Zoom IN/DOWN
    # ticked, or after a run auto-fills the csv) - unless another primary operation owns the run.
    try:
        if csv_file_var.get().strip() != '' and not (aggregate_lemmatized_var.get()
                                                     or extract_nouns_verbs_from_CoNLL_var.get()):
            annotate_file_checkbox.configure(state='normal')
    except Exception:
        pass

csv_file_var.trace('w', refresh_annotate_state)

videos_lookup = {'No videos available':''}
videos_options='No videos available'

TIPS_lookup = {'csv files - Problems & solutions':'TIPS_NLP_csv files - Problems & solutions.pdf','Statistical measures':'TIPS_NLP_Statistical measures.pdf','Lexical databases (WordNet, VerbNet, FrameNet)': 'TIPS_NLP_Lexical databases (WordNet, VerbNet, FrameNet).pdf','The world of emotions and sentiments':'TIPS_NLP_The world of emotions and sentiments.pdf'}
TIPS_options = 'csv files - Problems & solutions','Statistical measures','Lexical databases (WordNet, VerbNet, FrameNet)','The world of emotions and sentiments'

# add all the lines to the end to every special GUI
# change the last item (message displayed) of each line of the function y_multiplier_integer = help_buttons
# any special message (e.g., msg_anyFile stored in GUI_IO_util) will have to be prefixed by GUI_IO_util.
webSearch = "\n\nYou can search terms directly on the WordNet website at http://wordnetweb.princeton.edu/perl/webwn?s=&sub=Search+WordNet."


def help_buttons(window, help_button_x_coordinate, y_multiplier_integer):
    if not IO_setup_display_brief:
        y_multiplier_integer = GUI_IO_util.place_help_button(window, help_button_x_coordinate,y_multiplier_integer,"NLP Suite Help",
                                      GUI_IO_util.msg_csv_txtFile)
        y_multiplier_integer = GUI_IO_util.place_help_button(window, help_button_x_coordinate,y_multiplier_integer,"NLP Suite Help",
                                      GUI_IO_util.msg_corpusData)
        y_multiplier_integer = GUI_IO_util.place_help_button(window, help_button_x_coordinate,y_multiplier_integer,"NLP Suite Help",
                                      GUI_IO_util.msg_outputDirectory)
    else:
        y_multiplier_integer = GUI_IO_util.place_help_button(window, help_button_x_coordinate,y_multiplier_integer,"NLP Suite Help",
                                      GUI_IO_util.msg_IO_setup)

    y_multiplier_integer = GUI_IO_util.place_help_button(window, help_button_x_coordinate, y_multiplier_integer, "NLP Suite Help",
                                  "The INPUT csv file widget will display the csv file required by many algorithms in this GUI.\n\n   1. The algorithms that require a csv file in input will prompt you to select the appropriate csv file when you tick a checkbox.\n\n   2. Some algorithms, when you run them, will automatically write in the csv filename produced.\n\n   3. You can always click the Select INPUT CSV file button to change the selection.\n" + GUI_IO_util.msg_openFile)
    y_multiplier_integer = GUI_IO_util.place_help_button(window,help_button_x_coordinate,y_multiplier_integer,"NLP Suite Help",
                                                         'Please, tick the \'GUIs available\' checkbox if you wish to see and select the range of other available tools, such as the CoNLL table analyzer or Word Sense Induction.')
    y_multiplier_integer = GUI_IO_util.place_help_button(window, help_button_x_coordinate, y_multiplier_integer, "NLP Suite Help",
                                  "Please, using the dropdown menu, select the Lexical category (NOUN or VERB) to aggregate.\n\nThis feeds the selected Knowledge base: WordNet (NOUN & VERB), VerbNet (VERB only), FrameNet (NOUN & VERB - including event nouns).\n\nLists of NOUNS and VERBS can be exported from a CoNLL table (POSTAG NN* for nouns, VB* for verbs - tick 'Extract nouns & verbs from CoNLL' to extract them)." + webSearch)
    y_multiplier_integer = GUI_IO_util.place_help_button(window, help_button_x_coordinate, y_multiplier_integer, "NLP Suite Help",
                                  "Please, using the dropdown menu, select the Knowledge base used to classify/aggregate the NOUNS and VERBS:\n\n- WordNet (NOUN & VERB): groups words into hierarchical synsets / top-level supersenses (e.g., 'walk', 'run', 'flee' as verbs of 'motion'; 'police', 'senator' under 'person').\n\n- VerbNet (VERB only): groups verbs into Levin classes by shared syntactic-semantic behaviour (e.g., 'murder', 'assassinate' in class 'murder-42.1').\n\n- FrameNet (NOUN & VERB): groups words into situational frames (e.g., 'kill', 'assassination' evoke the 'Killing' frame; includes event nouns).\n\n- * (all applicable): runs every resource that applies (VerbNet is skipped for NOUN).\n\nWordNet is hierarchical; VerbNet and FrameNet are flat membership look-ups. For VerbNet/FrameNet the most precise classification comes from the SRL (sense-disambiguated) route; the bare-lemma look-up here takes the first / most-basic class or frame." + webSearch)
    # y_multiplier_integer = GUI_IO_util.place_help_button(window, help_button_x_coordinate, y_multiplier_integer, "NLP Suite Help",
    #                               "Word Sense Disambiguation (WSD). Disambiguates each NOUN/VERB in its sentence context (Lesk; NLTK) and aggregates to the context-correct WordNet category — the precision alternative to the bare-lemma 'first sense.' INPUT: a CoNLL table. OUTPUT: each word with its disambiguated WordNet category + frequency csv/chart. WordNet-only (VerbNet/FrameNet use the SRL route). Distinct from the Word2Vec GUI's BERT Word Sense Induction, which discovers a word's senses in your corpus. Refs: Lesk 1986; Navigli 2009." + webSearch)
    y_multiplier_integer = GUI_IO_util.place_help_button(window, help_button_x_coordinate, y_multiplier_integer, "NLP Suite Help",
                                  "The 'CoNLL-based tools of semantic aggregation' button opens the CoNLL Table Analyzer GUI, handing it the CoNLL table of the corpus currently selected in your INPUT/OUTPUT configuration. There you can run the semantic-aggregation tools that need a CoNLL table: classify NOUNS and VERBS into WordNet, VerbNet, and FrameNet categories; Word Sense Disambiguation (WSD); and aggregation by sentence index.\n\nThe algorithm looks in the current OUTPUT directory for a CoNLL table matching your corpus and opens the analyzer already loaded with it - no need to hunt for the file.\n\nTick 'Run the default parser' to first parse your corpus: the button then opens the Parsers/Annotators GUI, which runs the configured parser (Stanford CoreNLP, Stanza, or spaCy - whichever is set in the Setup NLP package/language configuration) and, on completion, opens the CoNLL Table Analyzer loaded with the fresh CoNLL table. Leave it unticked to reuse a CoNLL table already present in the output directory.\n\nIf no CoNLL table is found and 'Run the default parser' is not ticked, you will be prompted to open the analyzer and select a CoNLL table manually." + webSearch)
    y_multiplier_integer = GUI_IO_util.place_help_button(window, help_button_x_coordinate, y_multiplier_integer, "NLP Suite Help",
                                  "Please, tick the checkbox if you wish to run the 'Zoom IN/DOWN' algorithm. It builds a list of related words from the selected Knowledge base:\n\n- WordNet (NOUN & VERB): from a starting synset (e.g., 'person') it goes DOWN the lexical hierarchy via hyponymy (X is a kind of Y) and meronymy (X is a part of Y) - e.g., 'person' yields 'police', 'woman', etc. NOUNS have 25 top-level synsets and VERBS have 15 (the 'Pick a category' dropdown).\n\n- VerbNet (VERB only): from a verb class (e.g., 'murder-42.1') or a member verb (e.g., 'murder'), it lists the member verbs of that class.\n\n- FrameNet (NOUN & VERB): from a frame (e.g., 'Killing') or a word, it lists the lexical units of that frame.\n\nFor WordNet you can use the 'Pick a category' dropdown or type a synset in 'Type a category'. For VerbNet/FrameNet, pick or type the class or frame.\n\nMultiple comma-separated starting values are allowed (e.g., 'person' and 'animal' for fairy tales where a talking fox is a social actor).\n\nPress the + button for multiple selections.\n\nPress RESET (or ESCape) to delete all values entered and start fresh.\n\nPress SHOW to display all selected values.\n\nIn INPUT all that is required is the starting keywords you select or enter; the algorithm uses only the lexical database (WordNet/VerbNet/FrameNet) and does not use the document(s) selected in your I/O configuration.\n\nIn OUTPUT the script creates a csv word list (and, for WordNet, a verbose multi-column file with the selected category, its definitions, sense frequencies, and examples of use)." + webSearch)
    # y_multiplier_integer = GUI_IO_util.place_help_button(window, help_button_x_coordinate, y_multiplier_integer, "NLP Suite Help",
    #                               "You can enter one or more comma-separated categories into the 'Type a category' field, ignoring the pre-selected dropdown values. Enter a WordNet synset (e.g., 'ethnic group' instead of 'person' to restrict to a lower level and get a much shorter list), a VerbNet class (e.g., 'murder-42.1') or member verb, or a FrameNet frame (e.g., 'Killing').\n\nPress OK when finished." + webSearch)
    y_multiplier_integer = GUI_IO_util.place_help_button(window, help_button_x_coordinate, y_multiplier_integer, "NLP Suite Help",
                                  "Please, tick the checkbox if you wish to annotate your input document(s) using a dictionary csv file generated by the \'Zoom IN\DOWN\' algorithm. Thus, you can extract all \'PERSON\' items from WordNet and annotate your corpus by those values.\n\nThe option automatically runs the default lemmatizer so that inflected forms are tagged too - e.g., a dictionary entry \'attack\' also tags \'attacked\', \'attacking\', \'Attack\' - each kept in its ORIGINAL form (the text itself is never changed to lemmas).\n\nIn INPUT the algorithm expects\n   1. either a single txt file or a directory of txt files to be annotated (txt file(s) are selected in the Setup INPUT/OUTPUT configuration widget);\n   2. a csv dictionary file generated by the ZOOM IN/DOWN widget and containing with the WordNet tags that will be used to annotate the text.\n\n   You will be prompted to select the csv file when you tick the checkbox.\n\nIn OUTPUT the algorithm produces an html file annotated according to the values found in the input csv dictionary file." + webSearch)
    y_multiplier_integer = GUI_IO_util.place_help_button(window, help_button_x_coordinate, y_multiplier_integer, "NLP Suite Help",
                                  "Please, tick the checkbox to run the 'Zoom OUT/UP' algorithm. It aggregates a csv list of LEMMATIZED NOUNS and VERBS into the categories of the selected Knowledge base:\n  - WordNet: top-level synsets / supersenses (e.g., run, flee, walk aggregated as verbs of 'motion'), climbing the hierarchy via hypernymy/holonymy;\n  - VerbNet: Levin verb classes (VERB only);\n  - FrameNet: situational frames (NOUN & VERB).\n\nYou can aggregate any list of LEMMATIZED nouns and verbs, however obtained - most likely from a CoNLL table (NOUNS have POSTAG NN*, VERBS VB*); tick 'Extract nouns & verbs from CoNLL' to extract the lists.\n\nIn INPUT, the script expects a csv file whose first column is a list of LEMMATIZED NOUNS or VERBS (the column header does not matter). You will be prompted to select the csv file when you tick the checkbox. Process either a NOUN list or a VERB list at a time, not both.\n\nIn OUTPUT, the script creates a csv file with each word's category + a frequency csv and chart.\n\nNOTE: For WordNet, the 'stative' category includes the auxiliary 'be' and 'possession' includes 'have'/'get' (you may wish to exclude these auxiliaries from frequencies). For VerbNet/FrameNet, the most precise classification comes from the SRL (sense-disambiguated) route; the bare-lemma look-up here takes the first / most-basic class or frame." + webSearch)
    # y_multiplier_integer = GUI_IO_util.place_help_button(window, help_button_x_coordinate, y_multiplier_integer, "NLP Suite Help",
    #                               "Please, tick the checkbox if you wish to extract all LEMMATIZED nouns and verbs from a CoNLL table (LEMMATIZED, since WordNet only contains lemmatized values) - nouns and verbs to be used by the 'Zoom OUT/UP' algorithm to aggregate nouns and verbs into WorNet categories.\n\nFor convenience, the script will also export the original words for nouns and verbs as found in FORM.\n\nIn INPUT, the script expects 2 csv files:\n  1. a csv CoNLL file;\n  2. a csv dictionary file containing the aggregated WordNet/VerbNet/FrameNet classification of LEMMATIZED words into higher-level aggregates (LEMMATIZED, since WordNet only contains lemmatized values). This file is generated by the 'Zoom OUT/UP' widget.\n\n   You will be prompted to select these csv files when you tick the checkbox.\n\nIn OUTPUT, the script produces a csv file and an Excel line plot of the aggregate WordNet/VerbNet/FrameNet categories by sentence index.")
    y_multiplier_integer = GUI_IO_util.place_help_button(window, help_button_x_coordinate, y_multiplier_integer, "NLP Suite Help",
                                  "Please, tick the checkbox if you wish to classify your document(s) by the selected Knowledge base (WordNet, VerbNet, or FrameNet).\n\nThe algorithm uses the default POS tagger to extract Nouns and Verbs to be then classified via the selected Knowledge base.\n\nIn INPUT the algorithm expects either a single txt file or a directory of txt files.\n\nIn OUTPUT the algorithm produces a csv file of nouns and verbs classified by the selected resource's categories.")
    # y_multiplier_integer = GUI_IO_util.place_help_button(window, help_button_x_coordinate, y_multiplier_integer, "NLP Suite Help",
    #                               "Please, tick the checkbox if you wish to run the Python 3 script 'Zoom OUT/UP by Sentence Index' to provide a csv file and an Excel line plot of the aggregate WordNet/VerbNet/FrameNet categories by sentence index for more in-grained linguistic analyses.\n\nIn INPUT, the algorithm expects 2 csv files:\n  1. a csv CoNLL file (you can select this file using the 'Select INPUT/OUTPUT configuration' widget or the 'Select INPUT CSV file' widget);\n  2. a csv dictionary file containing the aggregated WordNet/VerbNet/FrameNet classification of LEMMATIZED words into higher-level aggregates generated by the 'Zoom OUT/UP' widget (LEMMATIZED, since WordNet only contains lemmatized values) (you will be prompted to select this csv file when you tick the checkbox).\n\nIn OUTPUT, the script produces a csv file and an Excel line plot of the aggregate WordNet/VerbNet/FrameNet categories by sentence index.")
    y_multiplier_integer = GUI_IO_util.place_help_button(window, help_button_x_coordinate, y_multiplier_integer, "NLP Suite Help",
                                  GUI_IO_util.msg_openOutputFiles)
    return y_multiplier_integer -1
y_multiplier_integer = help_buttons(window, GUI_IO_util.help_button_x_coordinate, 0)

# change the value of the readMe_message

# GUI_util.select_inputFilename_button.configure(state="disabled")
readMe_message = "These scripts interface with the WordNet lexical database (bundled via NLTK — no separate download required) to find semantically related words.\n\nThe GUI widgets allow you to zoom IN/DOWN and zoom OUT/UP in the WordNet hierarchy and to display WordNet categories by sentence index.\n\nWhen zooming IN/DOWN, you take a closer look at a term, going down the hierarchy (e.g., 'person' would give a list of words such as 'police', 'woman', ... or anyone who is a member of the group 'person').\n\nWhen zooming OUT/UP, you find terms' higher-level aggregates (e.g., 'walk', 'run', 'flee' as verbs of a higher-level verb aggregate 'motion')." + webSearch + \
        "\n\nIn INPUT different algorithms in this GUI will use\n1. no files at all (e.g., Zoom IN/DOWN);\n2. a csv file (e.g., Zoom OUT/UP);\n3. a single txt file or set of txt files (e.g., Zoom OUT/UP (classify/aggregate input text document(s) ...))." \
        "\n\nIn OUTPUT the different algorithms produce\n1. HTML files (e.g., Annotate corpus (using csv output file from Zoom IN/DOWN));\n2. csv files (all other algorithms)."
readMe_command = lambda: GUI_IO_util.display_help_button_info("NLP Suite Help", readMe_message)
GUI_util.GUI_bottom(config_filename, config_input_output_numeric_options, y_multiplier_integer, readMe_command, videos_lookup, videos_options, TIPS_lookup, TIPS_options, IO_setup_display_brief, scriptName)

# GUI_bottom's activateRunButton would disable RUN until an I/O file is selected, but this hub
# validates the per-option input at RUN time (Zoom IN/DOWN needs none), so keep RUN enabled.
GUI_util.run_button.configure(state='normal')

reminders_util.checkReminder(
        config_filename,
        reminders_util.title_options_English_language_WordNet,
        reminders_util.message_English_language_WordNet,
        True)

do_not_repeat_language_warning = False

def activate_NLP_options(*args):
    global error, package_basics, package, language, language_var, language_list, y_multiplier_integer, do_not_repeat_language_warning
    # after update no display
    error, package, parsers, package_basics, language, package_display_area_value, package_display_area_value_new, encoding_var, export_json_var, memory_var, document_length_var, limit_sentence_length_var=GUI_util.setup_parsers_annotators(y_multiplier_integer, scriptName)
    language_list = [language]
    if language!='English':
        if language != 'English' and not do_not_repeat_language_warning:
            mb.showwarning(title='Warning',
                           message='The WordNet algorithms only work for the English language. Your selected language is ' + language + '.\n\nYou can use the Setup dropdown menu at the bottom of this GUI and select "Setup NLP package and corpus language" option to select a differnt language if have an English-language corpus.')
        do_not_repeat_language_warning = True

GUI_util.setup_menu.trace('w', activate_NLP_options)

activate_NLP_options()
GUI_util.window.mainloop()
